# Project Goal:
- Import production and permit data for company and create custom fields requested by CEO 
- Add geographic fields to be used with Tableau

## Read in Libraries and Data

In [1]:
import pandas as pd
import numpy as np
import geopandas as gp
import requests as req
import re

In [2]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"
pd.set_option('precision', 2)

In [3]:
permits = pd.read_csv("Raw Data/DI Magnum NewDrill Permits.CSV")
prod = pd.read_csv("Raw Data/Production Table.CSV")
counties = gp.read_file("zip://Raw Data/UScounties.zip")

## Clean Up Production DataFrame

In [4]:
prod.head()
prod["Producing Status"].value_counts()

,API/UWI,Operator Alias (Legacy),Well/Lease Name,Well Number,County/Parish,Reservoir,Production Type,Producing Status,Drill Type,Measured Depth (TD),...,Block,OCS Area,PGC Area,Operator (Reported),Survey,Entity ID,Last 12 Oil,Last 12 Gas,Last 12 Water,Other No.
0,42469344440000,"MAGNUM PRODUCING, LP",SPACEK UNIT,1,VICTORIA (TX),MIDDLE WILCOX,GAS,INACTIVE,V,9500.0,...,NaN,NaN,P-330,"MAGNUM PRODUCING, LP","HINES, D",130836314,NaN,NaN,NaN,0
1,42245328640000,"MAGNUM PRODUCING, LP",MCLEAN UNIT 4,4,JEFFERSON (TX),HETEROSTEGINA - DISPOSAL,OIL,ACTIVE,V,8560.0,...,NaN,NaN,P-330,"MAGNUM PRODUCING, LP",EL&RR RR CO,130833332,10822.0,NaN,0.0,0
2,42039333450000,"MAGNUM PRODUCING, LP",DUCROZ,1,BRAZORIA (TX),TOP OF FRIO,OIL,INACTIVE,V,11100.0,...,NaN,NaN,P-330,"MAGNUM PRODUCING, LP","DILLARD, N",130819038,NaN,NaN,NaN,0
3,42321324010000,"MAGNUM PRODUCING, LP",ANDERSON,3,MATAGORDA (TX),HUEBNER,OIL,ACTIVE,D,10600.0,...,NaN,NaN,P-330,"MAGNUM PRODUCING, LP","HALL, E",130785484,857.0,19409.0,171.0,0
4,0,"MAGNUM PRODUCING, LP",LA LUW 801958,NaN,(N/A) (LA),NaN,OIL,INACTIVE,U,NaN,...,NaN,NaN,NaN,"MAGNUM PRODUCING, L.P.",NaN,130769684,119.0,NaN,0.0,801958

INACTIVE                                  501
P & A                                     149
ACTIVE                                     65
WORKED OVER TO ANOTHER ZONE                52
TA                                         16
RECLASSIFIED TO ANOTHER TYPE OF ENTITY     10
ACTIVE INJ                                  9
CANCELLED                                   5
PERMIT                                      3
SHUT IN                                     1
APPLICATION FOR PERMIT TO DRILL             1
Name: Producing Status, dtype: int64

### Remove P&A Wells and API Trailing 0's

In [5]:
#filtering out wells that have already been P&A by magnum
prod = prod.loc[prod["Producing Status"]!='P & A']

prod["Producing Status"].value_counts()

INACTIVE                                  501
ACTIVE                                     65
WORKED OVER TO ANOTHER ZONE                52
TA                                         16
RECLASSIFIED TO ANOTHER TYPE OF ENTITY     10
ACTIVE INJ                                  9
CANCELLED                                   5
PERMIT                                      3
SHUT IN                                     1
APPLICATION FOR PERMIT TO DRILL             1
Name: Producing Status, dtype: int64

In [6]:
#testing to see if api number can be cleaned by dividing number by 10,000 to remove trailing 0's
test = prod["API/UWI"].iloc[0]

test

int(test/(10**4))

42469344440000

4246934444

In [7]:
#dividing each api by 10,000 to clean number and remove trailing 0's
prod["API/UWI"] = prod["API/UWI"].apply(lambda x: int(x/(10**4)))

In [8]:
prod.head()

,API/UWI,Operator Alias (Legacy),Well/Lease Name,Well Number,County/Parish,Reservoir,Production Type,Producing Status,Drill Type,Measured Depth (TD),...,Block,OCS Area,PGC Area,Operator (Reported),Survey,Entity ID,Last 12 Oil,Last 12 Gas,Last 12 Water,Other No.
0,4246934444,"MAGNUM PRODUCING, LP",SPACEK UNIT,1,VICTORIA (TX),MIDDLE WILCOX,GAS,INACTIVE,V,9500.0,...,NaN,NaN,P-330,"MAGNUM PRODUCING, LP","HINES, D",130836314,NaN,NaN,NaN,0
1,4224532864,"MAGNUM PRODUCING, LP",MCLEAN UNIT 4,4,JEFFERSON (TX),HETEROSTEGINA - DISPOSAL,OIL,ACTIVE,V,8560.0,...,NaN,NaN,P-330,"MAGNUM PRODUCING, LP",EL&RR RR CO,130833332,10822.0,NaN,0.0,0
2,4203933345,"MAGNUM PRODUCING, LP",DUCROZ,1,BRAZORIA (TX),TOP OF FRIO,OIL,INACTIVE,V,11100.0,...,NaN,NaN,P-330,"MAGNUM PRODUCING, LP","DILLARD, N",130819038,NaN,NaN,NaN,0
3,4232132401,"MAGNUM PRODUCING, LP",ANDERSON,3,MATAGORDA (TX),HUEBNER,OIL,ACTIVE,D,10600.0,...,NaN,NaN,P-330,"MAGNUM PRODUCING, LP","HALL, E",130785484,857.0,19409.0,171.0,0
4,0,"MAGNUM PRODUCING, LP",LA LUW 801958,NaN,(N/A) (LA),NaN,OIL,INACTIVE,U,NaN,...,NaN,NaN,NaN,"MAGNUM PRODUCING, L.P.",NaN,130769684,119.0,NaN,0.0,801958

### Create Cleaned County Column
* cleaned county column only has name and no state appended at the end

In [9]:
#clean county names | using test row to test logic
prod["County/Parish"].iloc[197][:-5]

prod["Cleaned County"] = prod["County/Parish"].apply(lambda x: x[:-5])

'AUSTIN'

In [10]:
prod.head()

,API/UWI,Operator Alias (Legacy),Well/Lease Name,Well Number,County/Parish,Reservoir,Production Type,Producing Status,Drill Type,Measured Depth (TD),...,OCS Area,PGC Area,Operator (Reported),Survey,Entity ID,Last 12 Oil,Last 12 Gas,Last 12 Water,Other No.,Cleaned County
0,4246934444,"MAGNUM PRODUCING, LP",SPACEK UNIT,1,VICTORIA (TX),MIDDLE WILCOX,GAS,INACTIVE,V,9500.0,...,NaN,P-330,"MAGNUM PRODUCING, LP","HINES, D",130836314,NaN,NaN,NaN,0,VICTORIA
1,4224532864,"MAGNUM PRODUCING, LP",MCLEAN UNIT 4,4,JEFFERSON (TX),HETEROSTEGINA - DISPOSAL,OIL,ACTIVE,V,8560.0,...,NaN,P-330,"MAGNUM PRODUCING, LP",EL&RR RR CO,130833332,10822.0,NaN,0.0,0,JEFFERSON
2,4203933345,"MAGNUM PRODUCING, LP",DUCROZ,1,BRAZORIA (TX),TOP OF FRIO,OIL,INACTIVE,V,11100.0,...,NaN,P-330,"MAGNUM PRODUCING, LP","DILLARD, N",130819038,NaN,NaN,NaN,0,BRAZORIA
3,4232132401,"MAGNUM PRODUCING, LP",ANDERSON,3,MATAGORDA (TX),HUEBNER,OIL,ACTIVE,D,10600.0,...,NaN,P-330,"MAGNUM PRODUCING, LP","HALL, E",130785484,857.0,19409.0,171.0,0,MATAGORDA
4,0,"MAGNUM PRODUCING, LP",LA LUW 801958,NaN,(N/A) (LA),NaN,OIL,INACTIVE,U,NaN,...,NaN,NaN,"MAGNUM PRODUCING, L.P.",NaN,130769684,119.0,NaN,0.0,801958,(N/A)

### Adding Latest BOE/month column

In [11]:
prod["Latest BOE"] = (prod["Latest Gas"]/6) + prod["Latest Oil"]

## Permits Table

In [12]:
permits.head()

,API 10/UWI,District,Filed Date,Approved Date,Expired Date,State/Province,County/Parish,Operator Alias (Legacy),Lease Name,Well Number,...,Bottom Hole Latitude (WGS84),Bottom Hole Longitude (WGS84),Lease Number,Permit Depth UOM,Permit Number,DI Basin,DI Play,DI Subplay,Operator Company Name,Operator Ticker
0,3000564345,SE,NaN,2019-12-13,2021-12-02,NM,CHAVES (NM),MAGNUM PROD,THE PEGGY FEDERAL,113,...,33.54,-104.14,326731,ft,TEMP86977488,NORTHWEST SHELF,NORTHWEST SHELF,NaN,"MAGNUM PRODUCING, LP",NaN
1,4245730898,3,2019-10-03,2019-10-08,2021-10-08,TX,TYLER (TX),MAGNUM PROD,BIG THICKET,1,...,30.56,-94.34,NaN,ft,857731,GULF COAST CENTRAL,NaN,NaN,"MAGNUM PRODUCING, LP",NaN
2,4203933345,3,2019-07-03,2019-07-05,2021-07-05,TX,BRAZORIA (TX),MAGNUM PROD,DUCROZ,1,...,28.90,-95.60,27788,ft,854812,GULF COAST CENTRAL,NaN,NaN,"MAGNUM PRODUCING, LP",NaN
3,4232132426,3,2019-06-25,2019-06-26,2021-06-26,TX,MATAGORDA (TX),MAGNUM PROD,TRULL,1,...,28.77,-96.26,NaN,ft,854558,GULF COAST CENTRAL,NaN,NaN,"MAGNUM PRODUCING, LP",NaN
4,4246934444,2,2019-05-23,2019-05-24,2021-05-24,TX,VICTORIA (TX),MAGNUM PROD,SPACEK UNIT,1,...,29.08,-96.98,290069,ft,853438,GULF COAST WEST,NaN,NaN,"MAGNUM PRODUCING, LP",NaN

In [13]:
#finding which wells in production tables exist in the new drill permits table by magnum
prod["API/UWI"].isin(permits["API 10/UWI"]).head(10)

0     True
1     True
2     True
3     True
4    False
5     True
6     True
7    False
8    False
9    False
Name: API/UWI, dtype: bool

### Creating Column to Track Which Wells were Drilled By Magnum
* formula will check if api number exists in the newdrill permits data table

In [14]:
#creating new column representing whether or not well in production table exists
prod["Magnum Drilled (Y/N)"] = prod["API/UWI"].isin(permits["API 10/UWI"])

In [15]:
#mapping truths and falses to yes or no
prod["Magnum Drilled (Y/N)"] = prod["Magnum Drilled (Y/N)"].map({True: "Y", False: "N"})

In [16]:
#looking at how many wells are marked yes versus length of the entire permits table
prod["Magnum Drilled (Y/N)"].value_counts()


prod["Magnum Drilled (Y/N)"].value_counts()['Y']
len(permits)

print("There are {} permits not found in new drill permits table".format(len(permits)- prod["Magnum Drilled (Y/N)"].value_counts()['Y']))

N    542
Y    121
Name: Magnum Drilled (Y/N), dtype: int64

121

198

There are 77 permits not found in new drill permits table

## Counties Shapefile Cleanup

In [17]:
counties.head()

,NAME,STATE_NAME,STATE_FIPS,CNTY_FIPS,FIPS,geometry
0,Lake of the Woods,Minnesota,27,077,27077,"POLYGON ((-95.34283 48.54668, -95.34105 48.715..."
1,Ferry,Washington,53,019,53019,"POLYGON ((-118.85163 47.94956, -118.84846 48.4..."
2,Stevens,Washington,53,065,53065,"POLYGON ((-117.43883 48.04412, -117.54219 48.0..."
3,Okanogan,Washington,53,047,53047,"POLYGON ((-118.97209 47.93915, -118.97406 47.9..."
4,Pend Oreille,Washington,53,051,53051,"POLYGON ((-117.43858 48.99992, -117.03205 48.9..."

In [18]:
len(counties)
counties["FIPS"].nunique()

3141

3141

### Reading in States Table Online with Postal Codes to Add to Counties Shapefile

In [19]:
stlink = 'https://www.nrcs.usda.gov/wps/portal/nrcs/detail/?cid=nrcs143_013696'
stTable = pd.read_html(req.get(stlink).content)[0]

In [20]:
stTable.head()

         Name Postal Code  FIPS
0     Alabama          AL   1.0
1      Alaska          AK   2.0
2     Arizona          AZ   4.0
3    Arkansas          AR   5.0
4  California          CA   6.0

### Joining Counties Shapefile with State Postal Codes and Cleaning up Duplicate Columns

In [21]:
counties = pd.merge(counties, stTable[["Name", "Postal Code"]], how = "left", left_on="STATE_NAME", right_on="Name")

In [22]:
counties.drop(columns = "Name", inplace=True)

In [23]:
counties.head()

,NAME,STATE_NAME,STATE_FIPS,CNTY_FIPS,FIPS,geometry,Postal Code
0,Lake of the Woods,Minnesota,27,077,27077,"POLYGON ((-95.34283 48.54668, -95.34105 48.715...",MN
1,Ferry,Washington,53,019,53019,"POLYGON ((-118.85163 47.94956, -118.84846 48.4...",WA
2,Stevens,Washington,53,065,53065,"POLYGON ((-117.43883 48.04412, -117.54219 48.0...",WA
3,Okanogan,Washington,53,047,53047,"POLYGON ((-118.97209 47.93915, -118.97406 47.9...",WA
4,Pend Oreille,Washington,53,051,53051,"POLYGON ((-117.43858 48.99992, -117.03205 48.9...",WA

### Cleaning County Names by Converting to UpperCase for Matching/Joining as a Primary Key

In [24]:
counties["NAME"] = counties["NAME"].apply(lambda x: x.upper())

In [25]:
counties[["Postal Code", "NAME", "FIPS"]]

     Postal Code                             NAME   FIPS
0             MN                LAKE OF THE WOODS  27077
1             WA                            FERRY  53019
2             WA                          STEVENS  53065
3             WA                         OKANOGAN  53047
4             WA                     PEND OREILLE  53051
5             ID                         BOUNDARY  16021
6             MT                          LINCOLN  30053
7             MT                         FLATHEAD  30029
8             MT                          GLACIER  30035
9             MT                            TOOLE  30101
10            MT                          LIBERTY  30051
11            MT                             HILL  30041
12            MT                         SHERIDAN  30091
13            ND                           DIVIDE  38023
14            ND                            BURKE  38013
15            ND                         RENVILLE  38075
16            ND                        BOTTINEAU  38009
17            ND                          ROLETTE  38079
18            ND                           TOWNER  38095
19            ND                         CAVALIER  38019
20            ND                          PEMBINA  38067
21            MN                          KITTSON  27069
22            MN                           ROSEAU  27135
23            MT                           BLAINE  30005
24            MT                         PHILLIPS  30071
25            MT                           VALLEY  30105
26            MT                          DANIELS  30019
27            WA                          WHATCOM  53073
28            ID                           BONNER  16017
29            ND                             WARD  38101
...          ...                              ...    ...
3111          AK                MATANUSKA-SUSITNA  02170
3112          AK                     WADE HAMPTON  02270
3113          AK                           BETHEL  02050
3114          AK                        ANCHORAGE  02020
3115          AK                  KENAI PENINSULA  02122
3116          AK                       DILLINGHAM  02070
3117          AK               LAKE AND PENINSULA  02164
3118          AK                           HAINES  02100
3119          AK                           JUNEAU  02110
3120          AK                    KODIAK ISLAND  02150
3121          AK                            SITKA  02220
3122          AK              WRANGELL-PETERSBURG  02280
3123          AK                KETCHIKAN GATEWAY  02130
3124          AK  PRINCE OF WALES-OUTER KETCHIKAN  02201
3125          AK                   ALEUTIANS EAST  02013
3126          AK                   ALEUTIANS WEST  02016
3127          HI                          KALAWAO  15005
3128          HI                            KAUAI  15007
3129          HI                         HONOLULU  15003
3130          HI                             MAUI  15009
3131          HI                           HAWAII  15001
3132          VA                     PITTSYLVANIA  51143
3133          VA                         DANVILLE  51590
3134          AK                   VALDEZ-CORDOVA  02261
3135          AK                          YAKUTAT  02282
3136          AK            SKAGWAY-HOONAH-ANGOON  02232
3137          AK                    YUKON-KOYUKUK  02290
3138          AK              SOUTHEAST FAIRBANKS  02240
3139          AK                           DENALI  02068
3140          CO                       BROOMFIELD  08014

[3141 rows x 3 columns]

In [26]:
prod.head(1)

,API/UWI,Operator Alias (Legacy),Well/Lease Name,Well Number,County/Parish,Reservoir,Production Type,Producing Status,Drill Type,Measured Depth (TD),...,Operator (Reported),Survey,Entity ID,Last 12 Oil,Last 12 Gas,Last 12 Water,Other No.,Cleaned County,Latest BOE,Magnum Drilled (Y/N)
0,4246934444,"MAGNUM PRODUCING, LP",SPACEK UNIT,1,VICTORIA (TX),MIDDLE WILCOX,GAS,INACTIVE,V,9500.0,...,"MAGNUM PRODUCING, LP","HINES, D",130836314,NaN,NaN,NaN,0,VICTORIA,NaN,Y

### Joining Production with Counties Data to Bring Over County FIPS Codes & Cleanup Duplicate Columns

In [27]:
prod = pd.merge(prod, counties[["Postal Code", "NAME", "FIPS"]], how = "left", left_on=["State", "Cleaned County"], right_on = ["Postal Code", "NAME"])

In [28]:
prod.drop(columns = ["Postal Code", "NAME"], inplace = True)

In [29]:
prod.head()

,API/UWI,Operator Alias (Legacy),Well/Lease Name,Well Number,County/Parish,Reservoir,Production Type,Producing Status,Drill Type,Measured Depth (TD),...,Survey,Entity ID,Last 12 Oil,Last 12 Gas,Last 12 Water,Other No.,Cleaned County,Latest BOE,Magnum Drilled (Y/N),FIPS
0,4246934444,"MAGNUM PRODUCING, LP",SPACEK UNIT,1,VICTORIA (TX),MIDDLE WILCOX,GAS,INACTIVE,V,9500.0,...,"HINES, D",130836314,NaN,NaN,NaN,0,VICTORIA,NaN,Y,48469
1,4224532864,"MAGNUM PRODUCING, LP",MCLEAN UNIT 4,4,JEFFERSON (TX),HETEROSTEGINA - DISPOSAL,OIL,ACTIVE,V,8560.0,...,EL&RR RR CO,130833332,10822.0,NaN,0.0,0,JEFFERSON,NaN,Y,48245
2,4203933345,"MAGNUM PRODUCING, LP",DUCROZ,1,BRAZORIA (TX),TOP OF FRIO,OIL,INACTIVE,V,11100.0,...,"DILLARD, N",130819038,NaN,NaN,NaN,0,BRAZORIA,NaN,Y,48039
3,4232132401,"MAGNUM PRODUCING, LP",ANDERSON,3,MATAGORDA (TX),HUEBNER,OIL,ACTIVE,D,10600.0,...,"HALL, E",130785484,857.0,19409.0,171.0,0,MATAGORDA,NaN,Y,48321
4,0,"MAGNUM PRODUCING, LP",LA LUW 801958,NaN,(N/A) (LA),NaN,OIL,INACTIVE,U,NaN,...,NaN,130769684,119.0,NaN,0.0,801958,(N/A),NaN,N,NaN

In [30]:
prod[prod["FIPS"].isna()]

,API/UWI,Operator Alias (Legacy),Well/Lease Name,Well Number,County/Parish,Reservoir,Production Type,Producing Status,Drill Type,Measured Depth (TD),...,Survey,Entity ID,Last 12 Oil,Last 12 Gas,Last 12 Water,Other No.,Cleaned County,Latest BOE,Magnum Drilled (Y/N),FIPS
4,0,"MAGNUM PRODUCING, LP",LA LUW 801958,NaN,(N/A) (LA),NaN,OIL,INACTIVE,U,NaN,...,NaN,130769684,119.0,NaN,0.0,801958,(N/A),NaN,N,NaN
217,0,"MAGNUM PRODUCING, LP",PAINTERS GAS UNIT,NaN,UNKNOWN (TX),3-G-1,GAS,INACTIVE,V,NaN,...,NaN,105561337,NaN,NaN,NaN,0,UNKNOWN,NaN,N,NaN

In [31]:
pd.options.display.max_columns = len(prod.columns)
prod.head()

,API/UWI,Operator Alias (Legacy),Well/Lease Name,Well Number,County/Parish,Reservoir,Production Type,Producing Status,Drill Type,Measured Depth (TD),Spud Date,First Prod Date,Last Prod Date,Months Produced,Cum Gas,Daily Gas,Cum Oil,Daily Oil,Latest Oil,Latest Gas,Cum Water,Cum BOE,DI Subplay,First Month Oil,First Month Gas,First 6 Oil,DI Basin,First 6 Gas,First 6 BOE,First 6 Water,DI Play,Prac IP Oil Daily,Prac IP BOE,Prac IP Gas Daily,Prac IP CFGED,Latest Water,Prior 12 Oil,Prior 12 Gas,Last Test Date,Prior 12 Water,Last Flow Pressure,Last WHSIP,2nd Month GOR,Latest GOR,Cum GOR,Last 12 Yield,2nd Month Yield,Latest Yield,Peak Gas,Peak Gas Month No.,Peak Oil,Peak Oil Month No.,Peak BOE,Peak BOE Month No.,Peak MMCFGE,Peak MMCFGE Month No.,Upper Perforation,Lower Perforation,Gas Gravity,Oil Gravity,Completion Date,Well Count,Max Active Wells,Gas Gatherer,Oil Gatherer,Lease Number,Gross Perforated Interval,True Vertical Depth,Field,State,District,AAPG Geologic Province,Section,Country,Township,Range,Surface Latitude (WGS84),Abstract,Surface Longitude (WGS84),Block,OCS Area,PGC Area,Operator (Reported),Survey,Entity ID,Last 12 Oil,Last 12 Gas,Last 12 Water,Other No.,Cleaned County,Latest BOE,Magnum Drilled (Y/N),FIPS
0,4246934444,"MAGNUM PRODUCING, LP",SPACEK UNIT,1,VICTORIA (TX),MIDDLE WILCOX,GAS,INACTIVE,V,9500.0,2019-06-19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GULF COAST WEST,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2020-11-19,NaN,3451.0,4600.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9270.0,9312.0,0.66,46.0,2020-02-23,1,NaN,"MAGNUM PRODUCING, LP","GULFMARK ENERGY, INC.",290069,42.0,NaN,HELEN GOHLKE,TX,02,TEXAS & LOUISIANA GULF COAST BASIN,NaN,USA,NaN,NaN,29.08,175,-96.98,NaN,NaN,P-330,"MAGNUM PRODUCING, LP","HINES, D",130836314,NaN,NaN,NaN,0,VICTORIA,NaN,Y,48469
1,4224532864,"MAGNUM PRODUCING, LP",MCLEAN UNIT 4,4,JEFFERSON (TX),HETEROSTEGINA - DISPOSAL,OIL,ACTIVE,V,8560.0,2018-05-08,2020-06-01,2020-12-01,7.0,NaN,NaN,10822.0,51.0,1566.0,NaN,0.0,10822.0,NaN,1618.0,NaN,9256.0,GULF COAST CENTRAL,0.0,9256.0,0.0,NaN,59.0,59.0,0.0,353806.0,0.0,NaN,NaN,2020-10-27,NaN,NaN,NaN,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,1828.0,2.0,1828.0,2.0,11.0,2.0,5961.0,6044.0,NaN,30.5,2019-06-29,1,1.0,"MAGNUM PRODUCING, LP","GULFMARK ENERGY, INC.",27819,83.0,NaN,BIG HILL,TX,03,TEXAS & LOUISIANA GULF COAST BASIN,373,USA,NaN,NaN,29.76,551,-94.26,NaN,NaN,P-330,"MAGNUM PRODUCING, LP",EL&RR RR CO,130833332,10822.0,NaN,0.0,0,JEFFERSON,NaN,Y,48245
2,4203933345,"MAGNUM PRODUCING, LP",DUCROZ,1,BRAZORIA (TX),TOP OF FRIO,OIL,INACTIVE,V,11100.0,2019-10-16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GULF COAST CENTRAL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019-11-11,1,NaN,NaN,NaN,27788,NaN,NaN,WILDCAT,TX,03,TEXAS & LOUISIANA GULF COAST BASIN,65,USA,NaN,NaN,28.90,60,-95.60,NaN,NaN,P-330,"MAGNUM PRODUCING, LP","DILLARD, N",130819038,NaN,NaN,NaN,0,BRAZORIA,NaN,Y,48039
3,4232132401,"MAGNUM PRODUCING, LP",ANDERSON,3,MATAGORDA (TX),HUEBNER,OIL,ACTIVE,D,10600.0,2017-03-08,2020-01-01,2020-10-01,7.0,19409.0,89.0,857.0,4.0,2.0,NaN,171.0,4092.0,NaN,197.0,3206.0,687.0,GULF COAST CENTRAL,19409.0,3922.0,138.0,NaN,7.0,33.0,159.0,198448.0,0.0,NaN,NaN,2020-01-22,NaN,NaN,NaN,23820.0,22647.61,22650.0,44.16,42.0,NaN,6151.0,4.0,197.0,1.0,1169.0,4.0,7.0,4.0,8781.0,8950.0,NaN,40.0,2020-01-09,1,1.0,"MAGNUM PRODUCING, LP","GULFMARK ENERGY, INC.",27736,169.0,NaN,"LUCKY, EAST",TX,03,TEXAS & LOUISIANA GULF COAST BASIN,NaN,USA,NaN,NaN,28.96,45,-95.98,NaN,NaN,P-330,"MAGNUM PRODUCING, LP","HALL, E",130785484,857.0,19409.0,171.0,0,MATAGORDA,NaN,Y,48321
4,0,"MAGNUM PRODUCING, LP",LA LUW 801958,NaN,(N/A) (LA),NaN,OIL,INACTIVE,U,NaN,NaN,2010-11-01,2012-01-01,2.0,NaN,NaN,322.0,NaN,119.0,NaN,0.0,322.0,NaN,203.0,NaN,203.0,NaN,0.0,203.0,0.0,NaN,4.0,4.0,0.0,23032.0,0.0,203.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,NaN,NaN,203.0,1.0,203.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,1,1.0,"GULF SOUTH PIPELINE COMPANY, LP","L & L TRANSPORTATION, LLC",NaN,NaN,NaN,"OAKLEY, NORTHWEST",LA,NaN,NaN,NaN,USA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"MAGNUM PRODUCING, L.P.",NaN,130769684,119.0,NaN,0.0,801958,(N/A),NaN,N,NaN

In [67]:
#finding rows with no lease name
prod[prod["Well/Lease Name"].isna()]

,API/UWI,Operator Alias (Legacy),Well/Lease Name,Well Number,County/Parish,Reservoir,Production Type,Producing Status,Drill Type,Measured Depth (TD),Spud Date,First Prod Date,Last Prod Date,Months Produced,Cum Gas,Daily Gas,Cum Oil,Daily Oil,Latest Oil,Latest Gas,Cum Water,Cum BOE,DI Subplay,First Month Oil,First Month Gas,First 6 Oil,DI Basin,First 6 Gas,First 6 BOE,First 6 Water,DI Play,Prac IP Oil Daily,Prac IP BOE,Prac IP Gas Daily,Prac IP CFGED,Latest Water,Prior 12 Oil,Prior 12 Gas,Last Test Date,Prior 12 Water,Last Flow Pressure,Last WHSIP,2nd Month GOR,Latest GOR,Cum GOR,Last 12 Yield,2nd Month Yield,Latest Yield,Peak Gas,Peak Gas Month No.,Peak Oil,Peak Oil Month No.,Peak BOE,Peak BOE Month No.,Peak MMCFGE,Peak MMCFGE Month No.,Upper Perforation,Lower Perforation,Gas Gravity,Oil Gravity,Completion Date,Well Count,Max Active Wells,Gas Gatherer,Oil Gatherer,Lease Number,Gross Perforated Interval,True Vertical Depth,Field,State,District,AAPG Geologic Province,Section,Country,Township,Range,Surface Latitude (WGS84),Abstract,Surface Longitude (WGS84),Block,OCS Area,PGC Area,Operator (Reported),Survey,Entity ID,Last 12 Oil,Last 12 Gas,Last 12 Water,Other No.,Cleaned County,Latest BOE,Magnum Drilled (Y/N),FIPS
56,4224130695,"MAGNUM PRODUCING, LP",NaN,1W,JASPER (TX),YEGUA 7300,SWD,CANCELLED,D,11357.0,2003-03-15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GULF COAST CENTRAL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7135.0,7833.0,NaN,NaN,NaN,1,NaN,NaN,NaN,000111278,698.0,NaN,BUNA,TX,03,TEXAS & LOUISIANA GULF COAST BASIN,65,USA,NaN,NaN,30.43,510,-94.02,NaN,NaN,P-330,"MAGNUM PRODUCING, LP",T&NO RR CO,128925762,NaN,NaN,NaN,0,JASPER,NaN,N,48241
73,4248101745,"MAGNUM PRODUCING, LP",NaN,3,WHARTON (TX),MIOCENE 4300,SWD,PERMIT,V,7777.0,1936-03-23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GULF COAST CENTRAL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3700.0,4800.0,NaN,NaN,1968-04-01,1,NaN,NaN,NaN,000105153,1100.0,NaN,LOUISE,TX,03,TEXAS & LOUISIANA GULF COAST BASIN,23,USA,NaN,NaN,29.06,287,-96.39,NaN,NaN,P-330,"MAGNUM PRODUCING, LP",M&C,128275019,NaN,NaN,NaN,0,WHARTON,NaN,N,48481
74,4240932532,"MAGNUM PRODUCING, LP",NaN,1,SAN PATRICIO (TX),4000,SWD,PERMIT,V,7423.0,1998-01-13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GULF COAST WEST,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2980.0,5820.0,NaN,NaN,1998-02-05,1,NaN,NaN,NaN,000104133,2840.0,NaN,TAFT,TX,04,TEXAS & LOUISIANA GULF COAST BASIN,NaN,USA,NaN,NaN,28.00,129,-97.42,7,NaN,P-330,"MAGNUM PRODUCING, LP","GARCIA, J",128274915,NaN,NaN,NaN,0,SAN PATRICIO,NaN,N,48409
75,4240901423,"MAGNUM PRODUCING, LP",NaN,2D,SAN PATRICIO (TX),3900,SWD,PERMIT,V,4015.0,1951-01-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GULF COAST WEST,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2850.0,4000.0,NaN,NaN,1987-07-06,1,NaN,NaN,NaN,000104815,1150.0,0.0,"TAFT, WEST",TX,04,TEXAS & LOUISIANA GULF COAST BASIN,NaN,USA,NaN,NaN,28.02,227,-97.39,NaN,NaN,P-330,"MAGNUM PRODUCING, LP","ROSS, R",128274357,NaN,NaN,NaN,0,SAN PATRICIO,NaN,N,48409
76,0,"MAGNUM PRODUCING, LP",NaN,3A,WHARTON (TX),MIOCENE 4300,SWD,CANCELLED,V,4800.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3700.0,4800.0,NaN,NaN,NaN,1,NaN,NaN,NaN,000105422,1100.0,NaN,LOUISE,TX,03,TEXAS & LOUISIANA GULF COAST BASIN,NaN,USA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,P-330,"MAGNUM PRODUCING, LP",NaN,128273620,NaN,NaN,NaN,0,WHARTON,NaN,N,48481
77,4240930559,"MAGNUM PRODUCING, LP",NaN,1M,SAN PATRICIO (TX),4000,SWD,CANCELLED,V,8565.0,1991-04-09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GULF COAST WEST,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2980.0,5820.0,NaN,NaN,NaN,1,NaN,NaN,NaN,000104134,2840.0,NaN,TAFT,TX,04,TEXAS & LOUISIANA GULF COAST BASIN,NaN,USA,NaN,NaN,28.00,129,-97.42,NaN,NaN,P-330,"MAGNUM PRODUCING, LP","GARCIA, J",128273299,NaN,NaN,NaN,0,SAN PATRICIO,NaN,N,48409
121,4229730256,"MAGNUM PRODUCING, LP",NaN,1,LIVE OAK (TX),WILCOX,SWD,CANCELLED,V,11600.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,EAGLE FORD DRY,NaN,NaN,NaN,GULF COAST WEST,NaN,NaN,NaN,EAGLEFORD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3950.0,4900.0,NaN,NaN,NaN,1,NaN,NaN,NaN,000096408,950.0,NaN,MCKINNEY,TX,02,TEXAS & LOUISIANA GULF COAST BASIN,NaN,USA,NaN,NaN,28.39,171,-98.02,NaN,NaN,P-330,"MAGNUM PRODUCING, LP","ELY, J",124485316,NaN,NaN,NaN,0,LIVE OAK,NaN,N,48297
126,4203931498,MAGNUM PRODUCING & OPERATING CO.,NaN,2,BRAZORIA (TX),FRIO F-28,SWD,CANCELLED,V,14005.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GULF COAST CENTRAL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4175.0,4300.0,NaN,NaN,NaN,1,NaN,NaN,NaN,000088732,125.0,NaN,FOUR CORNERS,TX,03,TEXAS & LOUISIANA GULF COAST BASIN,65,USA,NaN,NaN,29.00,26,-95.69,NaN,NaN,P-330,MAGNUM PRODUCING & OPERATING CO.,"AUSTIN, S F",124478838,NaN,NaN,NaN,0,BRAZORIA,NaN,N,48039

In [70]:
#dropping rows in table with no well name since they were all SWD wells that were permits or cancelled
prod.drop(index = prod[prod["Well/Lease Name"].isna()].index, inplace = True)

## Exporting Prepared Production Table to File

In [84]:
prod.to_excel("Data for Tableau - Do not Edit Files in Here/Prepared Production Table.xlsx", index = False)

<hr>

# Stopping Point - Code below is Irrelevant as of 6/25/21

<hr>

## Merging Well List with Sell Information

In [85]:
import os

In [86]:
sellInfoDF = pd.read_excel('VOID Well - Sell Intention - Table.xlsx')
sellInfoDF.drop(index = sellInfoDF[sellInfoDF["Well/Lease Name"].isna()].index, inplace = True)

In [87]:
#source code to add sheet to existing workbook is found here: 
#https://stackoverflow.com/questions/42370977/how-to-save-a-new-sheet-in-an-existing-excel-file-using-pandas

from openpyxl import load_workbook

#path of where excel file is to add sheet to
path = os.path.abspath('Data for Tableau - Do not Edit Files in Here/Prepared Production Table.xlsx')

book = load_workbook(path)
writer = pd.ExcelWriter(path, engine = 'openpyxl')
writer.book = book


sellInfoDF.to_excel(writer, sheet_name = 'Well Sale List', index = False)
writer.save()
writer.close()

# Merging Coworker's (Anish's) Version

In [79]:
#Storing sheet names needed to unify tables
sheets = pd.ExcelFile("Magnum TX RRC Sell Intention.xlsx").sheet_names[:3]
sheets

['Magnum Engineering', 'Magnum Operating, LLC', 'Magnum Producing, LP']

In [80]:
dfList = []


for sheet in sheets:
    temp = pd.read_excel('Magnum TX RRC Sell Intention.xlsx', header = 1, sheet_name=sheet)
    dfList.append(temp)
    
anishDF = pd.concat(dfList, sort=False)

In [93]:
sellInfoDF.head(2)
sellInfoDF.info()
anishDF.head(2)
anishDF.info()

,API/UWI,Well/Lease Name,Well Number,County/Parish,Sale Intention,Well Logs,Wellbore Diagram,Equipment List,Geological Presentation,LOS,Purchase Statements,Lease Exhibit,Executed P4 (Change of Operator),Executed Bill of Sale
0,1709901012,11000 RA SUA;HENRY MELANCON,001,ST. MARTIN (LA),SELL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,N
1,4201530644,A. SCHROEDER,1,AUSTIN (TX),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,N

<class 'pandas.core.frame.DataFrame'>
Int64Index: 445 entries, 0 to 444
Data columns (total 14 columns):
API/UWI                             445 non-null int64
Well/Lease Name                     445 non-null object
Well Number                         394 non-null object
County/Parish                       445 non-null object
Sale Intention                      49 non-null object
Well Logs                           0 non-null float64
Wellbore Diagram                    0 non-null float64
Equipment List                      0 non-null float64
Geological Presentation             0 non-null float64
LOS                                 0 non-null float64
Purchase Statements                 0 non-null float64
Lease Exhibit                       0 non-null float64
Executed P4 (Change of Operator)    445 non-null object
Executed Bill of Sale               445 non-null object
dtypes: float64(7), int64(1), object(6)
memory usage: 52.1+ KB

,API,Lease No.,Lease Name,Well No.,Operator Name,County,Status,Sale Intention,Field Name,On Schedule,Folder on Well File,Well Logs,Well Reports,Wellbore Diagram,Equipment List,Geological Presentation,LOS,Purchase Statements,Lease Exhibit,Executed P4 (Change of Operator),Executed Bill of Sale
0,4202532776,161800,ALGEA GAS UNIT,3,MAGNUM ENGINEERING COMPANY,BEE,NaN,NaN,"ORANGEDALE (LULING, LOWER)",N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,4202532776,212589,ALGEA GAS UNIT,3,MAGNUM ENGINEERING COMPANY,BEE,NaN,NaN,"THEIS, SOUTH(SLICK FIRST)",Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

<class 'pandas.core.frame.DataFrame'>
Int64Index: 789 entries, 0 to 606
Data columns (total 21 columns):
API                                 789 non-null int64
Lease No.                           789 non-null int64
Lease Name                          789 non-null object
Well No.                            789 non-null object
Operator Name                       789 non-null object
County                              789 non-null object
Status                              80 non-null object
Sale Intention                      0 non-null float64
Field Name                          789 non-null object
On Schedule                         789 non-null object
Folder on Well File                 44 non-null object
Well Logs                           1 non-null object
Well Reports                        1 non-null object
Wellbore Diagram                    2 non-null object
Equipment List                      0 non-null float64
Geological Presentation             1 non-null object
LOS                                 0 non-null float64
Purchase Statements                 0 non-null float64
Lease Exhibit                       7 non-null object
Executed P4 (Change of Operator)    0 non-null float64
Executed Bill of Sale               37 non-null object
dtypes: float64(5), int64(2), object(14)
memory usage: 135.6+ KB

In [82]:
leftTable = sellInfoDF[["API/UWI", "Well/Lease Name", "Sale Intention"]]
rightTable = anishDF.drop(columns=["Sale Intention", "Lease Name", "On Schedule"])
rightTable.rename(columns = {"API": "API/UWI"}, inplace = True)

In [83]:
mergedDF = pd.merge(leftTable, rightTable, how = "left", on = "API/UWI")
mergedDF

,API/UWI,Well/Lease Name,Sale Intention,Lease No.,Well No.,Operator Name,County,Status,Field Name,Folder on Well File,Well Logs,Well Reports,Wellbore Diagram,Equipment List,Geological Presentation,LOS,Purchase Statements,Lease Exhibit,Executed P4 (Change of Operator),Executed Bill of Sale
0,1709901012,11000 RA SUA;HENRY MELANCON,SELL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,4201530644,A. SCHROEDER,NaN,25654.0,1,"MAGNUM PRODUCING, LP",AUSTIN,NaN,BLEIBLERVILLE (WILCOX 9200),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,4201530644,A. SCHROEDER,NaN,27151.0,1,"MAGNUM PRODUCING, LP",AUSTIN,NaN,BLEIBLERVILLE (WILCOX 9000),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4201530644,A. SCHROEDER,NaN,172789.0,1,"MAGNUM PRODUCING, LP",AUSTIN,NaN,BLEIBLERVILLE (WILCOX 9540),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4250536460,"ALEXANDER ""A""",SELL,255119.0,3,"MAGNUM PRODUCING, LP",ZAPATA,NaN,EXSUN (LOBO CONS.),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,4250536379,"ALEXANDER ""A""",SELL,248176.0,2,"MAGNUM PRODUCING, LP",ZAPATA,NaN,EXSUN (LOBO CONS.),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,4250536309,"ALEXANDER ""A""",SELL,244496.0,1,"MAGNUM PRODUCING, LP",ZAPATA,NaN,EXSUN (LOBO CONS.),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,4250536309,"ALEXANDER ""A""",SELL,247748.0,1,"MAGNUM PRODUCING, LP",ZAPATA,NaN,BIG MAC (6470),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,4247940805,ALEXANDER RANCH,NaN,256324.0,1,"MAGNUM PRODUCING, LP",WEBB,NaN,VALLEY (NAVARRO),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,4202532833,ALGEA,NaN,165204.0,1,MAGNUM ENGINEERING COMPANY,BEE,NaN,MALCOMB (3608 HOCKLEY),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,4202532833,ALGEA,NaN,168121.0,1,MAGNUM ENGINEERING COMPANY,BEE,NaN,MALCOMB (1270),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,4202532776,ALGEA GAS UNIT,NaN,161800.0,3,MAGNUM ENGINEERING COMPANY,BEE,NaN,"ORANGEDALE (LULING, LOWER)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,4202532776,ALGEA GAS UNIT,NaN,212589.0,3,MAGNUM ENGINEERING COMPANY,BEE,NaN,"THEIS, SOUTH(SLICK FIRST)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,4232132401,ANDERSON,NaN,27736.0,3,"MAGNUM PRODUCING, LP",MATAGORDA,NaN,"LUCKY, EAST (HUEBNER)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,4232132361,ANDERSON,NaN,26834.0,1C,"MAGNUM PRODUCING, LP",MATAGORDA,NaN,LUCKY ( GOLA),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,4232132361,ANDERSON,NaN,275419.0,1T,"MAGNUM PRODUCING, LP",MATAGORDA,NaN,LUCKY (THOMPSON 10100),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,4232132383,ANDERSON-THOMPSON,NaN,27142.0,2,"MAGNUM PRODUCING, LP",MATAGORDA,NaN,WILDCAT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,4208932482,"ANDERSON, MARK N., ET UX",NaN,221747.0,1,"MAGNUM PRODUCING, LP",COLORADO,NaN,"CHESTERVILLE, NORTH (YEGUA 6000)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,4212330992,"ANGERSTEIN, H O",SELL,207897.0,1,"MAGNUM PRODUCING, LP",DE WITT,NaN,"COTTONWOOD CREEK, S. (FRIO 2300)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,4212331885,APACHE GAS UNIT,NaN,180694.0,1,"MAGNUM PRODUCING, LP",DE WITT,NaN,WENDLING (WILCOX 12850),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,4212331885,APACHE GAS UNIT,NaN,203190.0,1,"MAGNUM PRODUCING, LP",DE WITT,NaN,WENDLING (WILCOX 11200),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,4228532829,APPLING FARMS,NaN,181968.0,1,"MAGNUM PRODUCING, LP",LAVACA,NaN,VIENNA (8450),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,4223930213,"APPLING, F. E. -B-",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,4207131688,B.B. ROGERS GAS UNIT 1,NaN,22499.0,2,"MAGNUM PRODUCING, LP",CHAMBERS,NaN,WHITES BAYOU (F-16),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,4207131688,B.B. ROGERS GAS UNIT 1,NaN,22499.0,2T,"MAGNUM PRODUCING, LP",CHAMBERS,NaN,WHITES BAYOU (F-16),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,4207131688,B.B. ROGERS GAS UNIT 1,NaN,22499.0,2U,"MAGNUM PRODUCING, LP",CHAMBERS,NaN,WHITES BAYOU (F-16),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,4207131688,B.B. ROGERS GAS UNIT 1,NaN,177245.0,2-C,"MAGNUM PRODUCING, LP",CHAMBERS,NaN,WHITES BAYOU (F-15-C),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,4207131688,B.B. ROGERS GAS UNIT 1,NaN,201104.0,2C,"MAGNUM PRODUCING, LP",CHAMBERS,NaN,WHITES BAYOU (F-14),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,4229733915,"BAKER, EARL",NaN,132992.0,9A,"MAGNUM PRODUCING, LP",LIVE OAK,NaN,BAKER (LULING SD.),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,4229702494,"BAKER, EARL",NaN,127436.0,1A,"MAGNUM PRODUCING, LP",LIVE OAK,NaN,BAKER (WILCOX 10000),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
574,4208930440,"WEGENHOFT, JOHN AND FORD",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
575,4224731567,WEST COYOTE,NaN,109848.0,1,"MAGNUM PRODUCING, LP",JIM HOGG,NaN,"COYOTE, WEST (QUEEN CITY)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
576,302711440,"WHITEHEAD ""B""",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
577,302711458,"WHITEHEAD ""B""",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
578,302701139,"WHITEHEAD ""B""",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
579,4223933353,WILLIAMS,NaN,223863.0,1,"MAGNUM PRODUCING, LP",JACKSON,NaN,"MORALES, NORTH (MIDDLE WILCOX)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
580,4223933353,WILLIAMS,NaN,224928.0,1,"MAGNUM PRODUCING, LP",JACKSON,NaN,"MORALES, N. (9250)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
581,4229102452,"WILLIAMS, J. D.",NaN,1177.0,7,MAGNUM ENGINEERING COMPANY,LIBERTY,Shut in - Injection Well,"DAYTON, NORTH (5000 SAND)",No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
582,4229102467,"WILLIAMS, J. D.",NaN,1177.0,22,MAGNUM ENGINEERING COMPANY,LIBERTY,Injection Well,"DAYTON, NORTH (5000 SAND)",No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
583,4229102450,"WILLIAMS, J. D.",NaN,1177.0,5,MAGNUM ENGINEERING COMPANY,LIBERTY,Dry Hole - P&A - 10/2011,"DAYTON, NORTH (5000 SAND)",No (P&A Ltr in N Dayton Field folder,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
584,4229102457,"WILLIAMS, J. D.",NaN,1177.0,12,MAGNUM ENGINEERING COMPANY,LIBERTY,P&A - 12/2009,"DAYTON, NORTH (5000 SAND)",No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
585,4229102457,"WILLIAMS, J. D.",NaN,149260.0,12,MAGNUM ENGINEERING COMPANY,LIBERTY,P&A - 12/2009,"DAYTON, NORTH (5000 SAND)",No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
586,4229132222,"WILLIAMS, J. D. -C-",NaN,22711.0,26,MAGNUM ENGINEERING COMPANY,LIBERTY,Active,"DAYTON, NORTH (5000 SAND)",No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
587,4229132224,"WILLIAMS, J. D. -C-",NaN,155453.0,28,MAGNUM ENGINEERING COMPANY,LIBERTY,No prod info on RRC since 12/1997. Temp Abandoned,"DAYTON, NORTH (MIOCENE 2400)",No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
588,4229132097,"WILLIAMS, J. D. 'B'",NaN,189093.0,23,MAGNUM ENGINEERING COMPANY,LIBERTY,No prod info on RRC since 01/2004. Temp Abandoned,"DAYTON, NORTH (5000 SAND)",No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
589,4229132257,"WILLIAMS, J. D. ""D""",NaN,23140.0,29,MAGNUM ENGINEERING COMPANY,LIBERTY,Well shut in (Lease Producing),"DAYTON, NORTH (5000 SAND)",No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
590,4229132096,"WILLIAMS, J.D. -B-",NaN,20714.0,25,MAGNUM ENGINEERING COMPANY,LIBERTY,Well Inactive (Lease Producing),"DAYTON, NORTH (5000 SAND)",No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
591,4216730592,"WILSON, B. LOBIT",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
592,4201530132,"WINTERBOTHAM, JOHN M",NaN,23718.0,1,"MAGNUM PRODUCING, LP",AUSTIN,NaN,"NELSONVILLE ( WILCOX 9,200)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
593,4208930044,"WINTERMAN, ADA M.",NaN,194927.0,1,"MAGNUM PRODUCING, LP",COLORADO,NaN,RAMSEY (8600 WILCOX),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
594,4208930093,WINTERMANN,NaN,50040.0,2,"MAGNUM PRODUCING, LP",COLORADO,NaN,"RAMSEY, E. (WILCOX 9350)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
595,4203931452,"WITTJEN, GADDIS ET AL",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
596,4208932001,WOLF-GLASSCOCK GAS UNIT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
597,4208931333,YOUENS GAS UNIT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
598,4208930154,"YOUENS, W.T. GAS UNIT",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
599,4208930256,"ZAHRADNICK, ALFRED",NaN,91859.0,1,"MAGNUM PRODUCING, LP",COLORADO,NaN,"RAMSEY, E. (WILCOX 10300)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
600,4231732011,ZANT,NaN,62249.0,1,MAGNUM ENGINEERING COMPANY,MARTIN,NaN,ACKERLY (DEAN SAND),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
601,4211531212,"ZANT ""A""",NaN,62213.0,1,MAGNUM ENGINEERING COMPANY,DAWSON,NaN,ACKERLY (DEAN SAND),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
602,4231732059,"ZANT ""B""",NaN,62432.0,1,MAGNUM ENGINEERING COMPANY,MARTIN,NaN,ACKERLY (DEAN SAND),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
603,4212331934,ZENGERLE,NaN,200152.0,1,"MAGNUM PRODUCING, LP",DE WITT,NaN,BRANDT (WILCOX DEEP),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN